# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image for ARM64
  jobs:
  - job: BuildArm64
    displayName: Build Arm 64 on Self-Hosted
    pool:
      name: Arm64
    steps:
    - task: Docker@2
      displayName: Build image for ARM64 on Self-Host
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'novakiller/miraibot'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Mirai_Bot/Dockerfile ARM32'
        buildContext: '$(Build.SourcesDirectory)/Mirai_Bot/'
        tags: |
          arm32.$(tag)
          arm32
